from configs.DataConfig import SOURCE_DATA_CONFIG, TARGET_DATA_CONFIG, EVAL_DATA_CONFIG, TEST_DATA_CONFIG

SOURCE_DATA_CONFIG = SOURCE_DATA_CONFIG
TARGET_DATA_CONFIG = TARGET_DATA_CONFIG
EVAL_DATA_CONFIG = EVAL_DATA_CONFIG
TEST_DATA_CONFIG = TEST_DATA_CONFIG

SNAPSHOT_DIR = './log/train/2urban'
TEST_SAVE_PATH = './log/test/2urban/result'

# Hyper Paramters
WEIGHT_DECAY = 0.0005
LEARNING_RATE = 1e-2
MOMENTUM = 0.9
POWER = 0.9  # lr poly power

PSEUDO_SELECT = True
FIRST_STAGE_STEP = 4000  # for first stage
NUM_STEPS_STOP = 8001  # Use damping instead of early stopping
NUM_STEPS_MAX = 15000  # for learning rate poly
PREHEAT_STEPS = int(NUM_STEPS_MAX / 20)  # for warm-up
EVAL_EVERY = 1000
GENERATE_PSEDO_EVERY = 1000

LAMBDA1 = 1.5
LAMBDA2 = 0.8
LAMBDA3 = 0.8
LAMBDA4 = 0.9
